services:
  postgres:
    image: postgres:18.3-alpine3.22
    container_name: postgres
    environment:
      POSTGRES_USER: jobs
      POSTGRES_PASSWORD: postgress
      POSTGRES_DB: jobs
    ports:
      - "5432:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8
    container_name: redis
    ports:
      - "6379:6379"
#    volumes:
#      - redis_data:/data

#volumes:
#  postgres_data:
#  redis_data:
